version: '3'
services:
  ravelights-backend:
    container_name: ravelights-backend
    build: .
    restart: on-failure
    volumes:
      - .:/app
    network_mode: "host"
    command: python3 main.py --artnet-wifi --no-visualizer --no-audio --fps 30
    # devices:
    #   - "/dev/ttyAMA0:/dev/ttyAMA0" # Map serial port for artnet over serial
