[project]
name = "ravelights"
version = "0.1.0"
requires-python = "~=3.10"
dependencies = [
    "numpy == 1.26.1",
    "plum-py == 0.8.5",
    "Flask == 2.2.2",
    "Flask-RESTful == 0.3.9",
]

[project.optional-dependencies]
dev = [
    "pytest == 7.4.3",
    "mypy == 1.6.1",
    "ruff >= 0.1.3",
]
gui = [
    "pygame == 2.5.2",
]
serial = [
    "pyserial == 3.5.0",
]

[tool.setuptools]
package-dir = {"" = "src"}

[tool.setuptools.packages.find]
where = ["src"]

[tool.setuptools.package-data]
"*" = ["*"]

[build-system]
requires = ["setuptools>=42.0", "wheel", "pip >= 21.1"]
build-backend = "setuptools.build_meta"

[tool.ruff]
line-length = 120
target-version = "py311"
