[project]
name = "ravelights"
version = "0.1.0"
requires-python = "~=3.10"
dependencies = [
    "numpy == 1.26.3",
    "plum-py == 0.8.5",
    "Flask == 2.3.3",
    "Flask-RESTful == 0.3.10",
    "flask-socketio == 5.3.6",
    "requests == 2.31.0",
    "zeroconf == 0.128.0",
    "loguru == 0.7.2",
]

[project.optional-dependencies]
dev = [
    "pytest == 7.4.4",
    "pytest-flask == 1.3.0",
    "mypy == 1.8.0",
    "ruff >= 0.1.13",
]
gui = [
    "pygame == 2.5.2",
]
serial = [
    "pyserial == 3.5.0",
]

[tool.setuptools]
package-dir = {"" = "src"}

# include package data
# https://setuptools.pypa.io/en/latest/userguide/datafiles.html
[tool.setuptools.packages.find]
where = ["src"]

[tool.setuptools.package-data]
# include all files, this is also the default
"*" = ["*"]

[build-system]
requires = ["setuptools>=42.0", "wheel", "pip >= 21.1"]
build-backend = "setuptools.build_meta"

[tool.ruff]
line-length = 120
target-version = "py311"
